monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: error
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        error:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.error.log"
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            level: debug
            max_files: 10
            formatter: monolog.formatter.json
        access:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.access.log"
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            level: debug
            max_files: 180
            channels: ["request"]
            formatter: monolog.formatter.json
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
