monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: error
            excluded_http_codes: [404, 405]
        error:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.error.log"
            level: debug
            max_files: 10
        access:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.access.log"
            level: debug
            max_files: 180
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
            max_files: 10
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
